export const employerChats = [
   {
      id: 343363,
      applicant: "Алиса Алисова",
      resiver: 112,
      responded: true,
      status: null,
      isOnline: true,
      read: false,
      avatarUrl: "/images/chats/avatars/avatar1.png",
      lastMessage: "Добрый день! Подскажите, пожалуйста, возможно ли работать удалённо?",
      time: "13:58",
   },
   {
      id: 67585959,
      applicant: "Иван Иванов",
      resiver: 112,
      responded: true,
      status: null,
      isOnline: true,
      read: false,
      avatarUrl: "/images/chats/avatars/avatar2.png",
      lastMessage: "Высылаем вам тестовое задание https://docs.yandex.ru/docs/view?url=ya-disk-public%3A%2F%2Fs1BQCrQgRHYvKM0atnxeefbdOdrLWbAkaKPhDmsRhXRVOTcVUK%2FQoKqYv9Cd4b0wq%2FJ6bpmRyOJonT3VoXnDag%3D%3D&name=%D0%A2%D0%B5%D1%81%D1%82%D0%BE%D0%B2%D0%BE%D0%B5%20%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5.pdf",
      time: "вчера",
   },
   {
      id: 89567456346346,
      applicant: "Алиса Алисова",
      resiver: 112,
      responded: true,
      status: false,
      isOnline: false,
      read: true,
      avatarUrl: "/images/chats/avatars/avatar3.png",
      lastMessage: "",
      time: "01:03",
   },
   {
      id: 936688386200,
      applicant: "Петр Петров",
      resiver: 112,
      responded: true,
      status: true,
      isOnline: false,
      read: false,
      avatarUrl: "/images/chats/avatars/avatar4.png",
      lastMessage: "",
      time: "21:11",
   }
];

export const applicantChats = [
   {
      id: 343363644,
      employer: "Сбераналитика",
      resiver: 112,
      responded: true,
      status: null,
      isOnline: true,
      read: false,
      avatarUrl: "/images/chats/avatars/avatar1.png",
      lastMessage: "Добрый день! Мы рады, что вы откликнулись на нашу вакансию. Мы рассмотрим ваше резюме и вернёмся с ответом в течении 3 дней.",
      time: "12:00",
   },
   {
      id: 936688386200,
      employer: "Мой дом",
      resiver: 112,
      responded: true,
      status: true,
      isOnline: false,
      read: false,
      avatarUrl: "/images/chats/avatars/avatar4.png",
      lastMessage: "",
      time: "21:11",
   },
   {
      id: 67585959,
      employer: "ООО Клиника плюс",
      resiver: 112,
      responded: true,
      status: null,
      isOnline: true,
      read: false,
      avatarUrl: "/images/chats/avatars/avatar2.png",
      lastMessage: "Высылаем вам тестовое задание https://docs.yandex.ru/docs/view?url=ya-disk-public%3A%2F%2Fs1BQCrQgRHYvKM0atnxeefbdOdrLWbAkaKPhDmsRhXRVOTcVUK%2FQoKqYv9Cd4b0wq%2FJ6bpmRyOJonT3VoXnDag%3D%3D&name=%D0%A2%D0%B5%D1%81%D1%82%D0%BE%D0%B2%D0%BE%D0%B5%20%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5.pdf",
      time: "вчера",
   },
   {
      id: 89567456346346,
      employer: "Юндекс краунд",
      resiver: 112,
      responded: true,
      status: false,
      isOnline: false,
      read: true,
      avatarUrl: "/images/chats/avatars/avatar3.png",
      lastMessage: "",
      time: "01:03",
   }
];