export const vacanciesData = [
   {
      position: 'Мобильный коммуникационный дизайнер',
      employer: "Сбераналитика",
      id: 10001,
      city: 'Александровск-Сахалинский',
      remote_is_available: true,
      work_format: "Полная занятость",
      work_schedule: "Полный день",
      experience_from: 1,
      experience_to: 3,
      no_experience: false,
      salary_from: '100 000 ₽',
      salary_to: '140 000 ₽',
      datePublish: '',
      is_active: false,
      is_archived: true,
      is_moderated: false,
      avatarUrl: "/images/chats/avatars/avatar1.png",
      address: 'Московское шоссе 215',
   },
   {
      position: 'Ландшафтный дизайнер',
      employer: "ООО Клиника плюс",
      id: 10002,
      city: 'Подольск',
      address: 'Советская 15',
      remote_is_available: false,
      work_format: "Полная занятость",
      work_schedule: "Полный день",
      experience_from: 3,
      experience_to: 6,
      no_experience: false,
      salary_from: '100 000 ₽',
      salary_to: '170 000 ₽',
      datePublish: '',
      is_active: true,
      is_archived: false,
      is_moderated: false,
      avatarUrl: "/images/chats/avatars/avatar2.png",
   },
   {
      position: 'Водитель автобуса категории С, D, E',
      employer: "Мой дом",
      id: 10008,
      city: 'Санкт-Петербург',
      address: 'Лиговский 24',
      remote_is_available: false,
      work_format: "Полная занятость",
      work_schedule: "Вахта",
      experience_from: 2,
      experience_to: 5,
      no_experience: false,
      salary_from: '',
      salary_to: '',
      datePublish: '',
      is_active: true,
      is_archived: false,
      is_moderated: false,
      avatarUrl: "/images/chats/avatars/avatar4.png",
   },
   {
      position: 'DevOps Engeneer',
      employer: "ООО Клиника плюс",
      id: 10004,
      city: 'Выборг',
      address: 'Проспект Маркса 4',
      remote_is_available: true,
      work_format: "Проектная работа",
      work_schedule: "Сменный график",
      experience_from: 5,
      experience_to: 10,
      no_experience: false,
      salary_from: '170 000 ₽',
      salary_to:  '200 000 ₽',
      datePublish: '',
      is_active: false,
      is_archived: false,
      is_moderated: true,
      avatarUrl: "/images/chats/avatars/avatar2.png",
   },
   {
      position: 'Уборщик складских помещений',
      employer: "Юндекс краунд",
      id: 10005,
      city: 'Москва',
      address: 'Советская 48',
      remote_is_available: false,
      work_format: "Частичная занятость",
      work_schedule: "Сменный график",
      experience_from: 0,
      experience_to: 0,
      no_experience: true,
      salary_from: '50 000 ₽',
      salary_to:  '80 000 ₽',
      datePublish: '',
      is_active: false,
      is_archived: true,
      is_moderated: false,
      avatarUrl: "/images/chats/avatars/avatar3.png",
   },
   {
      position: 'QA тестировщик',
      employer: "ООО Клиника плюс",
      id: 10006,
      city: 'Москва',
      address: 'Ленина 35а',
      remote_is_available: true,
      work_format: "Полная занятость",
      work_schedule: "Гибкий график",
      experience_from: 0,
      experience_to: 3,
      no_experience: false,
      salary_from: '100 000 ₽',
      salary_to: '120 000 ₽',
      datePublish: '',
      is_active: true,
      is_archived: false,
      is_moderated: false,
      avatarUrl: "/images/chats/avatars/avatar2.png",
   },
   {
      position: 'Веб дизайнер',
      employer: "Мой дом",
      id: 10007,
      city: 'Москва',
      address: 'Гризодубовой 6',
      remote_is_available: false,
      work_format: "Стажировка",
      work_schedule: "Сменный график",
      experience_from: 5,
      experience_to: 10,
      no_experience: false,
      salary_from: '',
      salary_to: '',
      datePublish: '',
      is_active: true,
      is_archived: false,
      is_moderated: false,
      avatarUrl: "/images/chats/avatars/avatar4.png",
   },
   {
      position: 'Frontend-разработчик',
      employer: "Юндекс краунд",
      id: 10003,
      city: 'Санкт-Петербург',
      address: 'Авиастроителей 228',
      remote_is_available: false,
      work_format: "Полная занятость",
      work_schedule: "Полный день",
      experience_from: 6,
      experience_to: 8,
      no_experience: false,
      salary_from: '170 000 ₽',
      salary_to: '250 000 ₽',
      datePublish: '',
      is_active: false,
      is_archived: true,
      is_moderated: false,
      avatarUrl: "/images/chats/avatars/avatar3.png",
   },
  
   {
      position: 'Старший менеджер технического сопровождения проектов',
      employer: "ООО Клиника плюс",
      id: 10009,
      city: 'Москва',
      address: 'Тверская 20',
      remote_is_available: false,
      work_format: "Проектная работа",
      work_schedule: "Сменный график",
      experience_from: 1,
      experience_to: 3,
      no_experience: false,
      salary_from: '70 000 ₽',
      salary_to: '85 000 ₽',
      datePublish: '',
      is_active: true,
      is_archived: false,
      is_moderated: false,
      avatarUrl: "/images/chats/avatars/avatar2.png",
   },
   {
      position: 'Аналитик',
      employer: "Сбераналитика",
      id: 10010,
      city: 'Москва',
      address: 'Арбат 35д',
      address: 'Московское шоссе 215',
      remote_is_available: true,
      work_format: "Частичная работа",
      work_schedule: "Гибкий график",
      experience_from: 7,
      experience_to: 10,
      no_experience: false,
      salary_from: '190 000 ₽',
      salary_to: '210 000 ₽',
      datePublish: '',
      is_active: false,
      is_archived: false,
      is_moderated: true,
      avatarUrl: "/images/chats/avatars/avatar1.png",
   }
]

export const resumeData = [
   {
      id: "123124234",
      first_name: "Алиса",
      last_name: "Алисова",	      
      email: "alisson@gmail.com",
      phone: "2323232",
      job_title: "Веб-дизайнер",
      experience: {
         id: "54656465",
         responsibility: [],
         achievements: [],
         start_mont: 4,
         start_year: 2019,
         end_month: 7,
         end_year: 2020,
         to_date: [],
         company_name: [],
         profession: [],
         resume: [],
      },
      salary: '',
      city: 'Москва',
      remote_is_available: false,
      birth_date: '1990-06-14',
      photo: '/images/card/avatar.svg',
      no_experience: false,
   },
   {
      id: 67585959,
      applicant: "Иван Иванов",
      resiver: 112,
      responded: true,
      status: null,
      isOnline: true,
      read: false,
      avatarUrl: "/images/chats/avatars/avatar2.png",
      lastMessage: "Высылаем вам тестовое задание https://docs.yandex.ru/docs/view?url=ya-disk-public%3A%2F%2Fs1BQCrQgRHYvKM0atnxeefbdOdrLWbAkaKPhDmsRhXRVOTcVUK%2FQoKqYv9Cd4b0wq%2FJ6bpmRyOJonT3VoXnDag%3D%3D&name=%D0%A2%D0%B5%D1%81%D1%82%D0%BE%D0%B2%D0%BE%D0%B5%20%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5.pdf",
      time: "вчера",
   },
   {
      id: 89567456346346,
      applicant: "Алиса Алисова",
      resiver: 112,
      responded: true,
      status: false,
      isOnline: false,
      read: true,
      avatarUrl: "/images/chats/avatars/avatar3.png",
      lastMessage: "",
      time: "01:03",
   },
   {
      id: 936688386200,
      applicant: "Петр Петров",
      resiver: 112,
      responded: true,
      status: true,
      isOnline: false,
      read: false,
      avatarUrl: "/images/chats/avatars/avatar4.png",
      lastMessage: "",
      time: "21:11",
   }
];